### ISSUE TITLE
Refactor: refactor endpoints

### ISSUE THREAD

**Issue by anderssonk** [DH2643-2021-Group-1/Tripper#69]
* userId should be passed in as a query parameter
* firstName, lastName and such should _not_ be passed to endpoint
* editProfilePage should be a _put_ 
* edit blogpost should also be a _put_

**Comment by AdamJonsson** [comment]
Edit BlogPost is now a put #72

**Comment by AdamJonsson** [comment]
Profile related endpoints are fixed in #77
